import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { Header, Footer, ThemeProvider } from "@/components";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Leandro Ubilla Gonzalez - Web developer",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <div className={`flex flex-col min-h-screen font-inter`}>
            <Header />
            <main className={`flex-1`}>{children}</main>
            <Footer />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
